apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: tomcat-daemonset
  labels:
    app: tomcat

spec:
  selector:
    matchLabels:
      app: tomcat

  template:
    metadata:
      labels:
        app: tomcat

    spec:
      containers:
      - name: tomcat
        image: tomcat:9
        ports:
        - containerPort: 8080
