apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "150Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    ports:
    - containerPort: 80
