apiVersion: v1
kind: Pod
metadata:
  name: postgres-vol-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:15
    ports:
    - containerPort: 5432

    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD

    volumeMounts:
    - name: postgres-secret-volume
      mountPath: /etc/secrets
      readOnly: true

  volumes:
  - name: postgres-secret-volume
    secret:
      secretName: postgres-secret

  restartPolicy: Always
