apiVersion: v1
kind: Pod
metadata:
  name: economic-times-pod

spec:
  containers:
  - name: economic-app
    image: vinayak432/economic-times-app:5
    ports:
    - containerPort: 80

  imagePullSecrets:
  - name: dockerhub-secret
