apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
      - name: app-config
        mountPath: /etc/config
  volumes:
    - name: app-config
      configMap:
        name: app-config
