apiVersion: v1
kind: Service

metadata:
  name: nginx-loadbalancer-service

spec:
  type: LoadBalancer   

  selector:
    app: nginx        

  ports:
  - protocol: TCP
    port: 80           # External port
    targetPort: 80     # Pod containerPort
