apiVersion: batch/v1
kind: Job
metadata:
  name: script-file-job
spec:
  template:
    spec:
      containers:
      - name: runner
        image: ubuntu:22.04
        command: ["/bin/bash","/scripts/script.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: job-script
          defaultMode: 0755
      restartPolicy: Never

