apiVersion: v1
kind: Pod
metadata:
  name: jenkins-app
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    - containerPort: 50000
    volumeMounts:
    - mountPath: "/var/jenkins_home"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: my-pvc
