apiVersion: v1
kind: Service
metadata:
  name: jenkins-helm-svc
  namespace: jenkins-helm-ns
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
