apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jen-helm-pvc
  namespace: jenkins-helm-ns
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
