apiVersion: v1
kind: Pod
metadata:
  name: jenkins-hostpath
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    - containerPort: 50000
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-data
  volumes:
  - name: jenkins-data
    hostPath:
      path: /var/jenkins-data
      type: DirectoryOrCreate
