apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-efs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - jenkins
            topologyKey: "kubernetes.io/hostname"

      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: efs-vol
          mountPath: /var/jenkins_home

      volumes:
      - name: efs-vol
        persistentVolumeClaim:
          claimName: efs-test-pvc
