apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster
  template:
    metadata:
      labels:
        app: hamster
    spec:
      containers:
      - name: hamster
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - while true; do timeout 0.5s yes > /dev/null; sleep 0.5s; done
        resources:
          requests:
            cpu: 300m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi

